balancer:
  port: 8080
  health_check_interval: 10s
  failure_threshold: 8.0

backends:
  - host: "localhost"
    port: 8081
    weight: 100
  - host: "localhost"
    port: 8082
    weight: 100
  - host: "localhost"
    port: 8083
    weight: 100

pool:
  max_idle: 100
  max_active: 1000
  idle_timeout: 60s