version: '3.8'

services:
  load-balancer:
    build: .
    ports:
      - "8080:8080"
    networks:
      - lb-network
    depends_on:
      - backend1
      - backend2
      - backend3

  backend1:
    image: nginx:alpine
    ports:
      - "8081:80"
    networks:
      - lb-network
    volumes:
      - ./docker/nginx/index1.html:/usr/share/nginx/html/index.html:ro

  backend2:
    image: nginx:alpine
    ports:
      - "8082:80"
    networks:
      - lb-network
    volumes:
      - ./docker/nginx/index2.html:/usr/share/nginx/html/index.html:ro

  backend3:
    image: nginx:alpine
    ports:
      - "8083:80"
    networks:
      - lb-network
    volumes:
      - ./docker/nginx/index3.html:/usr/share/nginx/html/index.html:ro

networks:
  lb-network:
    driver: bridge